const API=window.NYAY_PATH_API||'/api';
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const getToken=()=>localStorage.getItem('nyaypath_token'); const api=async(path,opts={})=>{opts.headers={...(opts.headers||{}),...(getToken()?{Authorization:'Bearer '+getToken()}:{} )};const r=await fetch(API+path,opts);let d={};try{d=await r.json()}catch{}if(r.status===401){localStorage.removeItem('nyaypath_token');location.href='dashboard-login.html'}if(!r.ok)throw new Error(d.message||'Request failed');return d};
function logout(){
  localStorage.removeItem('nyaypath_token');
  location.href='login.html';

}function renderShell(user){const role=user.role;const label=role==='ADMIN'?'Admin Panel':role==='ADVOCATE'?'Advocate Portal':'Client Portal';document.body.innerHTML=`<div class="dash"><aside class="sidebar"><div class="brand"><span class="seal">न्या</span><div><strong>NYAY PATH</strong><small>${label}</small></div></div><nav class="side-nav"><a href="#dashboard">Dashboard</a>${role==='ADMIN'?'<a href="#bookings">Bookings</a><a href="#advocates">Advocates</a><a href="#users">Users</a>':''}${role==='ADVOCATE'?'<a href="#availability">Availability</a><a href="#requests">Requests</a>':''}${role==='CLIENT'?'<a href="#consultations">My Consultations</a>':''}<a href="index.html">View Website</a><a href="#" id="logout">Logout</a></nav></aside><main class="main"><div class="top"><div><h1>${role==='ADMIN'?'Admin Dashboard':role==='ADVOCATE'?'Advocate Dashboard':'My Dashboard'}</h1><p>Welcome, ${esc(user.name)}.</p></div><div class="user">${esc(user.email)}</div></div><div id="app"></div></main></div>`;$('#logout').onclick=e=>{e.preventDefault();logout()}}
async function admin(){const [o,b,a,u]=await Promise.all([api('/admin/overview'),api('/admin/bookings'),api('/admin/advocates'),api('/admin/users')]);$('#app').innerHTML=`<div class="grid"><div class="stat"><span>Clients</span><strong>${o.users}</strong></div><div class="stat"><span>Advocates</span><strong>${o.advocates}</strong></div><div class="stat"><span>Pending payments</span><strong>${o.pending}</strong></div><div class="stat"><span>Bookings</span><strong>${o.bookings}</strong></div></div><section class="section" id="bookings"><h2>Consultation Bookings</h2><div class="table-wrap"><table class="table"><thead><tr><th>Client</th><th>Advocate</th><th>Slot</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${b.bookings.map(x=>`<tr><td>${esc(x.client_name)}<br><small>${esc(x.client_phone)}</small></td><td>${esc(x.advocate_name)}</td><td>${x.date} · ${x.start_time}</td><td>${esc(x.payment_status)}<br>${esc(x.transaction_id)}</td><td>${esc(x.status)}</td><td>${x.payment_status==='PENDING'?`<button class="btn gold" onclick="pay('${x.id}','VERIFY')">Verify</button> <button class="btn light" onclick="pay('${x.id}','REJECT')">Reject</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6">No bookings.</td></tr>'}</tbody></table></div></section><section class="section" id="advocates"><h2>Advocates</h2><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Speciality</th><th>Status</th></tr></thead><tbody>${a.advocates.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.speciality)}</td><td>${x.verified?'Verified':'Pending'}</td></tr>`).join('')}</tbody></table></section><section class="section" id="users"><h2>Users</h2><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th></tr></thead><tbody>${u.users.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${x.role}</td></tr>`).join('')}</tbody></table></section>`}
async function pay(id,decision){try{await api('/admin/bookings/'+id+'/payment',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});await admin()}catch(e){alert(e.message)}}
async function advocate(){const [me,s,b]=await Promise.all([api('/auth/me'),api('/advocate/slots'),api('/advocate/bookings')]);$('#app').innerHTML=`<div class="grid"><div class="stat"><span>Profile</span><strong>${me.advocate?.verified?'Verified':'Pending'}</strong></div><div class="stat"><span>Active slots</span><strong>${s.slots.filter(x=>x.active).length}</strong></div><div class="stat"><span>Requests</span><strong>${b.bookings.length}</strong></div><div class="stat"><span>Speciality</span><strong>${esc(me.advocate?.speciality||'—')}</strong></div></div><section class="section" id="availability"><h2>Manage availability</h2><div class="form-grid"><div class="field"><label>Date</label><input id="sd" type="date" min="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Start</label><input id="ss" type="time"></div><div class="field"><label>End</label><input id="se" type="time"></div><div class="field" style="display:flex;align-items:end"><button class="btn gold" id="add">Add slot</button></div></div><div class="table-wrap" style="margin-top:18px"><table class="table"><thead><tr><th>Date</th><th>Time</th><th>Status</th><th>Action</th></tr></thead><tbody>${s.slots.map(x=>`<tr><td>${x.date}</td><td>${x.start_time}–${x.end_time}</td><td>${x.active?'Active':'Disabled'}</td><td>${x.active?`<button class="btn light" onclick="delSlot('${x.id}')">Disable</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="4">No slots.</td></tr>'}</tbody></table></div></section><section class="section" id="requests"><h2>Consultation Requests</h2><table class="table"><thead><tr><th>Client</th><th>Issue</th><th>Slot</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${b.bookings.map(x=>`<tr><td>${esc(x.client_name)}<br>${esc(x.client_phone)}</td><td>${esc(x.issue)}</td><td>${x.date} · ${x.start_time}</td><td>${x.payment_status}</td><td>${x.status}</td><td>${x.status==='CONFIRMED'?'—':`<button class="btn gold" onclick="setBook('${x.id}','CONFIRMED')">Accept</button> <button class="btn light" onclick="setBook('${x.id}','REJECTED')">Reject</button>`}</td></tr>`).join('')||'<tr><td colspan="6">No requests.</td></tr>'}</tbody></table></section>`;$('#add').onclick=async()=>{try{await api('/advocate/slots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:$('#sd').value,start_time:$('#ss').value,end_time:$('#se').value})});await advocate()}catch(e){alert(e.message)}}}
async function delSlot(id){try{await api('/advocate/slots/'+id,{method:'DELETE'});await advocate()}catch(e){alert(e.message)}} async function setBook(id,status){try{await api('/advocate/bookings/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await advocate()}catch(e){alert(e.message)}}
async function client(){const b=await api('/client/bookings');$('#app').innerHTML=`<section class="section" id="consultations"><h2>My Consultations</h2><div class="table-wrap"><table class="table"><thead><tr><th>Advocate</th><th>Service</th><th>Slot</th><th>Payment</th><th>Status</th></tr></thead><tbody>${b.bookings.map(x=>`<tr><td>${esc(x.advocate_name)}<br><small>${esc(x.speciality)}</small></td><td>${esc(x.service)}</td><td>${x.date} · ${x.start_time}</td><td>${x.payment_status}<br>${esc(x.transaction_id)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="5">No consultations yet. <a href="index.html#consultation">Book one</a></td></tr>'}</tbody></table></div></section>`}
(async()=>{if(!location.pathname.endsWith('admin-dashboard.html')&&!location.pathname.endsWith('advocate-dashboard.html')&&!location.pathname.endsWith('user-dashboard.html'))return;if(!getToken()){
  location.href='login.html';
  return;
}try{const {user}=await api('/auth/me');renderShell(user);if(user.role==='ADMIN')await admin();else if(user.role==='ADVOCATE')await advocate();else await client()}catch(e){alert(e.message)}})();
